export const ACTION_AUTH_LOGGED_IN = 'ACTION_AUTH_LOGGED_IN';

export const ACTION_USER_OPEN_CHAT_BOX = 'ACTION_USER_OPEN_CHAT_BOX';
export const ACTION_USER_SHOW_HOT_TOAST = 'ACTION_USER_SHOW_HOT_TOAST';
export const ACTION_USER_SNACKBAR = 'ACTION_USER_SNACKBAR';

export const ACTION_FOOD_GET_ALL_FOODS = 'ACTION_FOOD_GET_ALL_FOODS';
export const ACTION_FOOD_GET_ALL_FOODS_BY_NAME = 'ACTION_FOOD_GET_ALL_FOODS_BY_NAME';
export const ACTION_FOOD_GET_TYPE_CHOSEN = 'ACTION_FOOD_GET_TYPE_CHOSEN';
export const ACTION_FOOD_GET_ALL_TYPE_FOODS = 'ACTION_FOOD_GET_ALL_TYPE_FOODS';
export const ACTION_FOOD_MODAL_ADD_TYPE_FOOD = 'ACTION_FOOD_MODAL_ADD_TYPE_FOOD';
export const ACTION_FOOD_MODAL_EDIT_FOOD = 'ACTION_FOOD_MODAL_EDIT_FOOD';
export const ACTION_FOOD_MODAL_EDIT_TYPE_FOOD = 'ACTION_FOOD_MODAL_EDIT_TYPE_FOOD';

export const ACTION_ORDER_GET_ORDER = 'ACTION_ORDER_GET_ORDER';
export const ACTION_ORDER_ADD_FOODS = 'ACTION_ORDER_ADD_FOODS';
export const ACTION_ORDER_EDIT_FOODS = 'ACTION_ORDER_EDIT_FOODS';
export const ACTION_ORDER_DELETE_FOODS = 'ACTION_ORDER_DELETE_FOODS';
export const ACTION_ORDER_MODAL_INFORMATION_FOOD = 'ACTION_ORDER_MODAL_INFORMATION_FOOD';

export const ACTION_CUSTOMER_GET_ALL_CUSTOMERS = 'ACTION_CUSTOMER_GET_ALL_CUSTOMERS';
export const ACTION_CUSTOMER_GET_QUANTITY_CUSTOMERS = 'ACTION_CUSTOMER_GET_QUANTITY_CUSTOMERS';
export const ACTION_CUSTOMER_MODAL_ADD_CUSTOMER = 'ACTION_CUSTOMER_MODAL_ADD_CUSTOMER';
export const ACTION_CUSTOMER_MODAL_EDIT_CUSTOMER = 'ACTION_CUSTOMER_MODAL_EDIT_CUSTOMER';
export const ACTION_CUSTOMER_GET_ALL_CUSTOMERS_BY_KEYWORDS =
  'ACTION_CUSTOMER_GET_ALL_CUSTOMERS_BY_KEYWORDS';

export const ACTION_EMPLOYEE_GET_ALL_EMPLOYEES = 'ACTION_EMPLOYEE_GET_ALL_EMPLOYEES';
export const ACTION_EMPLOYEE_MODAL_ADD_EMPLOYEE = 'ACTION_EMPLOYEE_MODAL_ADD_EMPLOYEE';
export const ACTION_EMPLOYEE_MODAL_EDIT_EMPLOYEE = 'ACTION_EMPLOYEE_MODAL_EDIT_EMPLOYEE';
