export const ACTION_AUTH_LOGGED_IN = 'ACTION_AUTH_LOGGED_IN';

export const ACTION_USER_OPEN_CHAT_BOX = 'ACTION_USER_OPEN_CHAT_BOX';
export const ACTION_USER_SHOW_HOT_TOAST = 'ACTION_USER_SHOW_HOT_TOAST';
export const ACTION_USER_SNACKBAR = 'ACTION_USER_SNACKBAR';
export const ACTION_USER_GET_USER = 'ACTION_USER_GET_USER';
export const ACTION_USER_BOX_PROFILE = 'ACTION_USER_BOX_PROFILE';
export const ACTION_USER_BOX_NOTIFICATION = 'ACTION_USER_BOX_NOTIFICATION';
export const ACTION_USER_BACKDROP = 'ACTION_USER_BACKDROP';
export const ACTION_USER_CHOOSE_NOTIFICATION = 'ACTION_USER_CHOOSE_NOTIFICATION';
export const ACTION_USER_SUPPORT_CHOOSE_NOTIFICATION = 'ACTION_USER_SUPPORT_CHOOSE_NOTIFICATION';

export const ACTION_FOOD_GET_ALL_FOODS = 'ACTION_FOOD_GET_ALL_FOODS';
export const ACTION_FOOD_GET_ALL_FOODS_BY_NAME = 'ACTION_FOOD_GET_ALL_FOODS_BY_NAME';
export const ACTION_FOOD_GET_TYPE_CHOSEN = 'ACTION_FOOD_GET_TYPE_CHOSEN';
export const ACTION_FOOD_GET_ALL_TYPE_FOODS = 'ACTION_FOOD_GET_ALL_TYPE_FOODS';
export const ACTION_FOOD_MODAL_ADD_TYPE_FOOD = 'ACTION_FOOD_MODAL_ADD_TYPE_FOOD';
export const ACTION_FOOD_MODAL_EDIT_FOOD = 'ACTION_FOOD_MODAL_EDIT_FOOD';
export const ACTION_FOOD_MODAL_EDIT_TYPE_FOOD = 'ACTION_FOOD_MODAL_EDIT_TYPE_FOOD';
export const ACTION_FOOD_SORT_FOOD = 'ACTION_FOOD_SORT_FOOD';

export const ACTION_ORDER_GET_ORDER = 'ACTION_ORDER_GET_ORDER';
export const ACTION_ORDER_ADD_FOODS = 'ACTION_ORDER_ADD_FOODS';
export const ACTION_ORDER_EDIT_FOODS = 'ACTION_ORDER_EDIT_FOODS';
export const ACTION_ORDER_DELETE_FOODS = 'ACTION_ORDER_DELETE_FOODS';
export const ACTION_ORDER_SET_FOOD = 'ACTION_ORDER_SET_FOOD';
export const ACTION_ORDER_MODAL_INFORMATION_FOOD = 'ACTION_ORDER_MODAL_INFORMATION_FOOD';
export const ACTION_ORDER_GET_USER = 'ACTION_ORDER_GET_USER';
export const ACTION_ORDER_GET_BOOKS_BY_KEYWORD = 'ACTION_ORDER_GET_BOOKS_BY_KEYWORD';
export const ACTION_ORDER_MODAL_EDIT_BOOK = 'ACTION_ORDER_MODAL_EDIT_BOOK';
export const ACTION_ORDER_SORT_BOOK = 'ACTION_ORDER_SORT_BOOK';
export const ACTION_ORDER_NEW_BOOKS = 'ACTION_ORDER_NEW_BOOKS';
export const ACTION_ORDER_UPDATE_FOODS_FOR_BOOK = 'ACTION_ORDER_UPDATE_FOODS_FOR_BOOK';
export const ACTION_ORDER_BOOK_PAY_ORDER = 'ACTION_ORDER_BOOK_PAY_ORDER';

export const ACTION_CUSTOMER_GET_ALL_CUSTOMERS = 'ACTION_CUSTOMER_GET_ALL_CUSTOMERS';
export const ACTION_CUSTOMER_GET_QUANTITY_CUSTOMERS = 'ACTION_CUSTOMER_GET_QUANTITY_CUSTOMERS';
export const ACTION_CUSTOMER_MODAL_ADD_CUSTOMER = 'ACTION_CUSTOMER_MODAL_ADD_CUSTOMER';
export const ACTION_CUSTOMER_MODAL_EDIT_CUSTOMER = 'ACTION_CUSTOMER_MODAL_EDIT_CUSTOMER';
export const ACTION_CUSTOMER_GET_ALL_CUSTOMERS_BY_KEYWORDS =
  'ACTION_CUSTOMER_GET_ALL_CUSTOMERS_BY_KEYWORDS';
export const ACTION_CUSTOMER_GET_NEW_CUSTOMER_IN_WEEK = 'ACTION_CUSTOMER_GET_NEW_CUSTOMER_IN_WEEK';
export const ACTION_CUSTOMER_GET_GENDER_CUSTOMER = 'ACTION_CUSTOMER_GET_GENDER_CUSTOMER';
export const ACTION_CUSTOMER_GET_SORT_CUSTOMER = 'ACTION_CUSTOMER_GET_SORT_CUSTOMER';

export const ACTION_EMPLOYEE_GET_ALL_EMPLOYEES = 'ACTION_EMPLOYEE_GET_ALL_EMPLOYEES';
export const ACTION_EMPLOYEE_MODAL_ADD_EMPLOYEE = 'ACTION_EMPLOYEE_MODAL_ADD_EMPLOYEE';
export const ACTION_EMPLOYEE_MODAL_EDIT_EMPLOYEE = 'ACTION_EMPLOYEE_MODAL_EDIT_EMPLOYEE';
export const ACTION_EMPLOYEE_GET_EMPLOYEES_BY_KEYWORDS =
  'ACTION_EMPLOYEE_GET_EMPLOYEES_BY_KEYWORDS';
export const ACTION_EMPLOYEE_SORT_EMPLOYEE = 'ACTION_EMPLOYEE_SORT_EMPLOYEE';

export const ACTION_AREA_MODAL_ADD_AREA = 'ACTION_AREA_MODAL_ADD_AREA';
export const ACTION_AREA_GET_ALL_AREAS = 'ACTION_AREA_GET_ALL_AREAS';
export const ACTION_AREA_MODAL_EDIT_AREA = 'ACTION_AREA_MODAL_EDIT_AREA';
